base_url = "https://musicalfieldsforever.com"

title = "MusicalFieldsForever"

description = "Musical Fields Forever"

generate_feed = false

compile_sass = true

highlight_code = false

build_search_index = false

[extra]
